export const PIXI_TICKER_TARGET_FPMS = 0.06

export const INTERPOLATION_PULL_BACK_SPEED_RATIO = 0.3

export const GAME_SCREEN_WIDTH = 1200
export const GAME_SCREEN_HEIGHT = 800

export const GAME_SCREEN_CENTER = { x: GAME_SCREEN_WIDTH / 2, y: GAME_SCREEN_HEIGHT / 2 }

export const SPRITE_HEIGHT = 30

export const BASE_PLAYER_SPEED = 100
